name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          pwd
          ls
          npm ci

      - name: Sync Capacitor
        run: |
          pwd
          ls node_modules/@capacitor
          ./node_modules/.bin/cap sync ios

      - name: Build iOS
        run: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO
